backend:
  name: github
  repo: MateuszZaniewski/AstroKancelaria #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://kancelaria-komenda.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: /blog/{{slug}}
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: source, label: Image Source, widget: string }
      - { name: bigsource, label: Big Image Source, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: category, label: Category, widget: string }
      - { name: body, label: Content, widget: markdown }
