backend:
  name: git-gateway
  branch: main # Nazwa gałęzi, na której pracujesz (np. main)

media_folder: "public/images" # Folder, gdzie będą przechowywane pliki multimedialne
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/pages/blog" # Folder z plikami bloga
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }



backend:
  name: github
  repo: MateuszZaniewski/AstroKancelaria #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://kancelaria-komenda.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: koszta, label: Wydatki }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
